# Site settings
title: Rocky Mountain Hang Gliding and Paragliding Association
email: webmaster@rmhpa.org
description: "RMHPA is a club for free flight pilots in Colorado."
baseurl: "/rmhpa.github.io"
#url: "http://rmhpa.github.io/website/"

# Build settings
markdown: kramdown
permalink: pretty
